baseurl = "http://log.schroetersa.ch/"
languageCode = "en-us"
title = "Skywalker13"
theme = "ezhil"
paginate = 8
copyright = "ðŸ‡¨ðŸ‡­ Copyright Â© 2008-2024, Mathieu Schroeter"

pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[markup.goldmark.renderer]
  unsafe = true

[params]
  customCSS = "css/custom.css"
  customDarkCSS = "css/customDark.css"
  customJS = ["js/katex.min.js", "js/auto-render.min.js", "js/custom.js"]
  Mode = "dark"
  Subtitle = "Diary of an ex-GeeXboX developerâ€¦"
  featherIconsCDN = false

[[menu.main]]
  name = "/home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "/usr/posts"
  url = "/posts"
  weight = 2

[[menu.main]]
  name = "/usr/about"
  url = "/about"
  weight = 3

[[menu.main]]
  name = "/var/tags"
  url = "/tags"
  weight = 4

[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/Skywalker13"

[[params.social]]
  name = "RSS"
  icon = "rss"
  url = "/index.xml"

[taxonomies]
   tag = "tags"
